Feature/27 dmitriy dankov/dz 5
Evan-Kork/temabit-lections-2019 pull request #101
Opened 2019-10-28 17:57 UTC by Ar1dan7

2019-10-28 19:08 UTC, NeverSmileMan requested changes

2019-10-28 19:08 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/css/index.css
> +    width: 85%;
зачем ширина в %?

2019-10-28 19:08 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/css/index.css
> +    width: 350px;
а тут лучше в %, а то чуть поменял ширину окна браузера - всё перекосило

2019-10-28 19:08 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/index.html
> +                >
табуляция

2019-10-28 19:08 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/index.html
> +                >
отступы

2019-10-28 19:08 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/index.html
> +            </form>
лишний абзац

2019-10-28 19:08 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/index.html
> +        >
отступы, 
и если сносишь ">" на новую строку со слешем выглядит лучше "/>" (но это не ошибка)

2019-10-28 19:08 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/css/index.css
> +}
тут табуляция, ниже пробелами отступы

2019-10-28 19:08 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/index.html
> +                        >
отсюда и ниже отличается оформление input'ов

2019-10-31 13:25 UTC, Ar1dan7 commented on 27-dmitriy-dankov/dz-5/css/index.css
> +    width: 85%;
в пикселях как раз оно ломает расположение строчки при смене размерах окна а в процентах сохраняется соотношение

2019-10-31 13:26 UTC, Ar1dan7 commented on 27-dmitriy-dankov/dz-5/css/index.css
> +    width: 350px;
тут согласен, исправил

2019-10-31 13:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/css/index.css
> +    width: 85%;
я неправильно выразился, я имел ввиду зачем она вообще нужна?
что тебе это даёт? 
![image](https://user-images.githubusercontent.com/56158584/67951900-1175c180-fbf5-11e9-9404-019c6977132a.png)
вот так без него:
![image](https://user-images.githubusercontent.com/56158584/67951960-2f432680-fbf5-11e9-912e-d257104c0fb0.png)

2019-11-06 21:18 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-5/index.html
> +    <div class="form-anket">
отсюда и по 158 подвинь на таб

2019-11-07 18:56 UTC, closed without merging