dz-6
Evan-Kork/temabit-lections-2019 pull request #121
Opened 2019-11-02 22:36 UTC by oleg-ferenets

2019-11-02 23:37 UTC, mironenk0 approved these changes

2019-11-03 09:36 UTC, tryguba approved these changes

2019-11-03 16:27 UTC, NeverSmileMan requested changes

2019-11-03 16:27 UTC, NeverSmileMan commented on 02-oleg-ferenets/dz-6/index.html
> +</head>
забыл кой чего
https://developer.mozilla.org/ru/docs/Mozilla/Mobile/Viewport_meta_tag

2019-11-03 16:27 UTC, NeverSmileMan commented on 02-oleg-ferenets/dz-6/index.html
> +</html>
тут ничего не смущает?) или это норм страницу между head и body ставить?
строки пустые зачем

2019-11-03 19:29 UTC, NeverSmileMan requested changes

2019-11-03 19:29 UTC, NeverSmileMan commented on 02-oleg-ferenets/dz-6/index.html
> +                <h2>Заказать проект</h2>
как у заголовка заказать чего?) ссылку добавь

2019-11-03 20:12 UTC, NeverSmileMan requested changes

2019-11-03 20:12 UTC, NeverSmileMan commented on 02-oleg-ferenets/dz-6/index.html
> +            <h3><a href="#">Садовые участки</h3></p>
дважды тег а не закрыл

2019-11-03 21:46 UTC, NeverSmileMan approved these changes

2019-11-05 13:51 UTC, Evan-Kork commented on 02-oleg-ferenets/dz-6/index.html
> +                </p>
Тут щось зайве

2019-11-05 21:12 UTC, oleg-ferenets commented on 02-oleg-ferenets/dz-6/index.html
> +                </p>
Дякую, виправив.

2019-11-08 14:06 UTC, Evan-Kork approved these changes

2019-11-08 23:40 UTC, merged