feature/07-mikhail-biloshkyrskiyy/dz10
Evan-Kork/temabit-lections-2019 pull request #208
Opened 2019-11-27 17:05 UTC by GrefferM

2019-11-27 20:41 UTC, qPrutp approved these changes
пиши код з ; а то важко читати

2019-11-27 20:42 UTC, Hud-Vlad approved these changes

2019-11-30 08:28 UTC, Sun1ive commented on 07-mikhail-biloshkyrskiyy/dz-10/assets/script/main.js
> +// Selectors
Без сторонних библиотек

2019-11-30 08:29 UTC, Sun1ive requested changes
Нужно сделать на нативном JS

2019-12-04 09:14 UTC, Sun1ive approved these changes
за функциональщину респект, но думай о людях в команде которые так не пишут, и не смогут поддерживать такой код :)

2019-12-04 09:14 UTC, merged