feature/02-oleg-ferenets/dz-10
Evan-Kork/temabit-lections-2019 pull request #209
Opened 2019-11-27 19:17 UTC by oleg-ferenets

dz-10

2019-11-28 05:50 UTC, mironenk0 approved these changes

2019-11-28 11:16 UTC, tryguba approved these changes

2019-11-30 08:30 UTC, Sun1ive requested changes

2019-11-30 08:30 UTC, Sun1ive commented on 02-oleg-ferenets/dz-10/js1.js
> +function removeElements(array, ...items) {
рест оператор не проходили, нужно сделать без него

2019-12-02 21:54 UTC, oleg-ferenets commented
удаляю

2019-12-02 21:54 UTC, closed without merging