feature/01-oleh-tryhuba/dz-10
Evan-Kork/temabit-lections-2019 pull request #211
Opened 2019-11-28 11:15 UTC by tryguba

2019-11-28 11:29 UTC, mironenk0 approved these changes

2019-11-28 13:56 UTC, oleg-ferenets approved these changes

2019-11-28 18:32 UTC, Sun1ive requested changes

2019-11-28 18:32 UTC, Sun1ive commented on 01-oleh-tryhuba/dz-10/index.js
> +const unique = arr => [...new Set(arr)];
Без сэтов и спрэдов пожалуйста :)
Только на массивах и циклах.

2019-11-28 18:32 UTC, Sun1ive commented on 01-oleh-tryhuba/dz-10/index.js
> +		return false === arr2.includes(item, 0);
второй аргумент не обязательный если начинаем с 0
и false === arr2.includes(item, 0); тоже самое, что !arr2.includes();

2019-11-28 18:32 UTC, Sun1ive commented on 01-oleh-tryhuba/dz-10/index.js
> +		for (let j = 0; j < arr2.length; j++) {
норм, но перепиши на forEach, для закрепления

2019-11-28 18:32 UTC, Sun1ive commented on 01-oleh-tryhuba/dz-10/index.js
> +const removeElements = (arr, ...arr2) => {
rest оператор пока не проходили. подумай как сделать без него.

2019-12-01 09:46 UTC, tryguba commented on 01-oleh-tryhuba/dz-10/index.js
> +const removeElements = (arr, ...arr2) => {
подумав))

2019-12-01 09:46 UTC, tryguba commented on 01-oleh-tryhuba/dz-10/index.js
> +		for (let j = 0; j < arr2.length; j++) {
переписав..

2019-12-01 09:49 UTC, tryguba commented on 01-oleh-tryhuba/dz-10/index.js
> +		return false === arr2.includes(item, 0);
ок

2019-12-01 09:55 UTC, tryguba commented on 01-oleh-tryhuba/dz-10/index.js
> +const unique = arr => [...new Set(arr)];
випрвив))

2019-12-02 08:37 UTC, Sun1ive commented on 01-oleh-tryhuba/dz-10/index.js
> +		}
Обьясни что делает это выражение

2019-12-02 11:23 UTC, tryguba commented on 01-oleh-tryhuba/dz-10/index.js
> +		}
якщо в args[0] -  ( це перший массив який ми передали в функцію) є arguments[index], то
методом splice() змінюємо вміст масиву, видаляючи існуючі. Я поняв, що сильно накрутив, тому переписав цю функцію))

2019-12-04 09:15 UTC, Sun1ive approved these changes

2019-12-04 09:15 UTC, merged