feature/20-kostyleckiy-roman/dz-10
Evan-Kork/temabit-lections-2019 pull request #213
Opened 2019-11-28 15:49 UTC by NCrys

2019-11-28 16:53 UTC, AlexZ2019 approved these changes

2019-11-28 17:27 UTC, OlhaRedko approved these changes

2019-11-29 10:49 UTC, masaulenko approved these changes

2019-12-04 09:16 UTC, Sun1ive requested changes

2019-12-04 09:16 UTC, Sun1ive commented on 20-kostileckiy-roman/dz-10/1task.js
> +        if(a !== -1){
тут можно сразу в if проверять на -1, без промежуточной переменной

2019-12-04 09:16 UTC, Sun1ive commented on 20-kostileckiy-roman/dz-10/1task.js
> +        }else{break}
else не нужен

2019-12-04 09:16 UTC, Sun1ive commented on 20-kostileckiy-roman/dz-10/1task.js
> +            }else{break}
else не нужен-

2019-12-04 09:16 UTC, Sun1ive commented on 20-kostileckiy-roman/dz-10/1task.js
> +            let a = array.indexOf(items[i])
та же история что и в первом примере с indexof

2019-12-04 09:16 UTC, Sun1ive commented on 20-kostileckiy-roman/dz-10/1task.js
> +function removeItems(array, ...items){
rest оператор пока не проходили. подумай как сделать без него

2019-12-04 09:16 UTC, Sun1ive commented on 20-kostileckiy-roman/dz-10/1task.js
> +        while(true){
тут явно бесконечный цикл не нужен, нужно переделать без него)

2019-12-04 09:16 UTC, Sun1ive commented on 20-kostileckiy-roman/dz-10/1task.js
> +        return false === arr2.includes(item, 0);
false === includes() тоже что и return !includes()

2019-12-04 09:16 UTC, Sun1ive commented on 20-kostileckiy-roman/dz-10/1task.js
> +      while (true) {
та же история, что и выше
если не выйдет по другому, как вариант пойдет

2019-12-08 17:00 UTC, Sun1ive approved these changes

2019-12-08 17:00 UTC, merged