Feature/34 mykhailo vaskivnyuk/dz 10
Evan-Kork/temabit-lections-2019 pull request #214
Opened 2019-11-28 17:18 UTC by vaskivnyuk

ready for review

2019-11-29 11:19 UTC, kovrix approved these changes

2019-11-29 17:10 UTC, IYuRiKI approved these changes

2019-12-04 14:36 UTC, Sun1ive requested changes

2019-12-04 14:36 UTC, Sun1ive commented on 34-mykhailo-vaskivnyuk/dz-10/script.js
> +function removeValues(array, ...values) {
без рэст операторов

2019-12-05 09:29 UTC, vaskivnyuk commented on 34-mykhailo-vaskivnyuk/dz-10/script.js
> +function removeValues(array, ...values) {
замінив

2019-12-05 11:19 UTC, Sun1ive approved these changes

2019-12-05 11:19 UTC, merged