feature/03-alexander-mironenko/dz-10
Evan-Kork/temabit-lections-2019 pull request #218
Opened 2019-11-29 06:50 UTC by mironenk0

2019-11-29 09:37 UTC, tryguba approved these changes

2019-12-01 21:50 UTC, oleg-ferenets approved these changes

2019-12-02 06:23 UTC, Sun1ive requested changes

2019-12-02 06:23 UTC, Sun1ive commented on 03-alexander-mironenko/dz-10/js.js
> +function removeElements(array, ...items) {
без рест операторов

2019-12-04 10:02 UTC, mironenk0 commented on 03-alexander-mironenko/dz-10/js.js
> +function removeElements(array, ...items) {
Виправив

2019-12-04 10:20 UTC, Sun1ive approved these changes

2019-12-04 10:21 UTC, merged