feature/35-evgeniy-kovrukov/dz-10
Evan-Kork/temabit-lections-2019 pull request #220
Opened 2019-11-29 14:44 UTC by kovrix

https://codesandbox.io/s/distracted-http-hj11e

2019-11-29 14:48 UTC, mykhailo-vaskivnyuk approved these changes

2019-11-29 17:08 UTC, IYuRiKI approved these changes

2019-11-30 08:27 UTC, Sun1ive requested changes

2019-11-30 08:27 UTC, Sun1ive commented on 35-evgeniy-kovrukov/dz-10/index.js
> +function removeEach(array, ...item){
рест оператор пока не проходили, нужно сделать без него.

2019-11-30 08:27 UTC, Sun1ive commented on 35-evgeniy-kovrukov/dz-10/index.js
> +		return false === array2.includes(item, 0);
false === includes(), тоже самое, что и !includes()
второй аргумент не передаем если начинаем с 0 индекса

2019-11-30 08:27 UTC, Sun1ive commented on 35-evgeniy-kovrukov/dz-10/index.js
> +		return true !== array2.includes(item, 0);
тоже самое, что и выше

2019-12-03 07:55 UTC, kovrix commented on 35-evgeniy-kovrukov/dz-10/index.js
> +		return false === array2.includes(item, 0);
done

2019-12-03 07:55 UTC, kovrix commented on 35-evgeniy-kovrukov/dz-10/index.js
> +		return true !== array2.includes(item, 0);
done

2019-12-03 07:56 UTC, kovrix commented on 35-evgeniy-kovrukov/dz-10/index.js
> +function removeEach(array, ...item){
done

2019-12-04 09:17 UTC, Sun1ive requested changes

2019-12-04 09:17 UTC, Sun1ive commented on 35-evgeniy-kovrukov/dz-10/index.js
> +	var args = [].slice.call(arguments);
Array.from(arguments)

2019-12-04 09:26 UTC, kovrix commented on 35-evgeniy-kovrukov/dz-10/index.js
> +	var args = [].slice.call(arguments);
понял

2019-12-04 10:21 UTC, Sun1ive approved these changes

2019-12-04 10:21 UTC, merged