feature/24-olga-redko/dz-10
Evan-Kork/temabit-lections-2019 pull request #221
Opened 2019-11-30 16:51 UTC by OlhaRedko

2019-11-30 16:56 UTC, AlexZ2019 approved these changes

2019-12-01 10:08 UTC, masaulenko approved these changes

2019-12-01 13:04 UTC, NCrys approved these changes

2019-12-02 09:53 UTC, Sun1ive requested changes

2019-12-02 09:53 UTC, Sun1ive commented on 24-olga-redko/dz-10/script.js
> +function removeElements(array, ...items) {
Мы пока рэст оператор не проходили, нужно сделать без него :)

2019-12-02 13:45 UTC, OlhaRedko commented on 24-olga-redko/dz-10/script.js
> +function removeElements(array, ...items) {
Переделала :)

2019-12-04 09:18 UTC, Sun1ive approved these changes

2019-12-04 09:18 UTC, merged