Feature/10-yevhen-derevyanko/dz-10
Evan-Kork/temabit-lections-2019 pull request #223
Opened 2019-12-02 11:44 UTC by Yevhen96

2019-12-02 13:08 UTC, maverik1003 approved these changes

2019-12-02 13:43 UTC, merry-granger approved these changes

2019-12-04 09:19 UTC, Sun1ive requested changes

2019-12-04 09:19 UTC, Sun1ive commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +        if(arguments[iterToRemove] && arguments[0].indexOf(arguments[iterToRemove]) != -1){
Это работает, но это прям очень плохо выглядит :)
Сделай масив из агрументов, проитерируйся по нему и удали нужный элемент :)

2019-12-09 08:42 UTC, Sun1ive requested changes

2019-12-09 08:42 UTC, Sun1ive commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +    if(array.indexOf(itemToRemove) != -1){
можно оптимизировать через поиск индекса до проверки

2019-12-09 08:42 UTC, Sun1ive commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +    for (let i = 0; i < arg.length; i++) {
тут лучше начать поиск не с 0 элемента и не удалять из массива перед циклом

2019-12-09 08:42 UTC, Sun1ive commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +    for (let l = 0; l < arrLong.length; l++) {
тут замени на forEach

2019-12-09 08:42 UTC, Sun1ive commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +    for (let i = 0; i < array.length; i++) {
заменить на forEach

2019-12-09 08:42 UTC, Sun1ive commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +    if(array.indexOf(itemToRemove) != -1){
можно так же заменить на forEach

2019-12-10 13:52 UTC, Yevhen96 commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +    for (let i = 0; i < array.length; i++) {
зробив

2019-12-10 13:52 UTC, Yevhen96 commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +    for (let l = 0; l < arrLong.length; l++) {
зробив

2019-12-10 13:53 UTC, Yevhen96 commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +    for (let i = 0; i < arg.length; i++) {
виправив

2019-12-10 13:53 UTC, Yevhen96 commented on 10-yevhen-derevyanko/dz-10/js/script.js
> +    if(array.indexOf(itemToRemove) != -1){
виправив

2019-12-11 18:12 UTC, Sun1ive approved these changes
почисти комменты и можешь мержить

2019-12-11 20:07 UTC, Yevhen96 commented
почистив

2019-12-11 20:07 UTC, merged