TS  project
Evan-Kork/temabit-lections-2019 pull request #280
Opened 2020-07-13 08:15 UTC by NeverSmileMan

TS  project

2020-07-13 11:06 UTC, tryguba approved these changes

2020-07-13 13:32 UTC, masaulenko approved these changes

2020-07-13 13:55 UTC, qPrutp commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-map/departments-map.tsx
> +  let history = useHistory();
не по темі ts але вже не в першому проекті бачу let history, чому не const

2020-07-13 15:47 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-map/departments-map.tsx
> +  let history = useHistory();
![image](https://user-images.githubusercontent.com/56158584/87324653-10917f80-c539-11ea-9cbe-61a856cd7ab3.png)
потому что let подразумевает что я буду его модифицировать (картинка с официальной доки, решил не придумывать колесо)

2020-07-14 06:39 UTC, masaulenko commented on 26-sergey-urdinets/ts-project/src/components/pages/info/info-services/info-services.tsx
> +
функция validateLog используеться в двух файлах, ее можно вынести в отдельный файл для удобства

2020-07-14 06:49 UTC, masaulenko commented on 26-sergey-urdinets/ts-project/src/components/pages/info/info-services/info-services.tsx
> +
меня смутило что ты делаешь валидацию после plainToClass, а если выпадет ошибка то plainToClass будет лишним шагом. Хотя с другой стороны валидировать джейсон тоже не очень. Вобщем я бы при отправке данных делала валидацию, но могу ошибаться.

2020-07-17 07:59 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/package.json
> +  "devDependencies": {
После
npm install
npm run dev
выдало ошибку "Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'"
Пришлось вручную устанавливать "@babel/compat-data"

2020-07-17 09:36 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/package.json
> +  "devDependencies": {
не понятно почему не установился этот пакет, он в зависимостях "@babel/preset-env"
(на моём компе всё норм устанавливается, на рабочем - нет)

2020-07-20 14:14 UTC, kol-93 requested changes

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +          setSearchResults(data.result);
А какой смысл сохранять полученные невалидные данные в состоянии компонента?

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-map/simple-map/marker.tsx
> +    setShow(!isShow);
isShow - замыкается один раз с первым значением (false). потому onMarkerClick будет всегда делать setShow(true)

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-map/departments-map.tsx
> +  let history = useHistory();
**let** подразумевает, что будет изменено значение переменной. **history.push()** не является изменением значения переменной, а вызовом метода (который может повлечь изменение ее внутреннего мира, а может и не повлечь). более того, результаты хуков (стейт, рефы, ...), для своей-же безопасности делают через **const**, дабы самому случайно не начать их менять...

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +            next={() =>
в общем-то не страшно, с точки зрения функционала, но переписывание стрелочными функциями пропсов влечет за собой ненужные перерендеры дочерних компонентов.

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/info/info-services/info-services.tsx
> +
валидация **сырых данных** (а результат запроса - сырые данные) делается только после **plainToClass**, иначе валидатор не сможет понять, что именно ему валидировать, так что тут все правильно.

Но, как я уже писал в другом комменте, не понятно, зачем обновлять стейт невалидными данными

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +  } else if (bool) {
что такое **bool**

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +      (item) => ~item.adress.search(new RegExp(value, 'i'))
зачем тут побитовое отрицание?
что будет искать, если в value будет что-то типа "(helo|world)"

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +    setTableState(data.slice(0, 20));
Что такое 20? Почему размер пагнации не обьявлен хотя-бы именованной константой (а лучше - параметром в Props)?

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/search-ttn/result-output/result-output.tsx
> +function getImg(status: string) {
говорили же за **enum**-ы

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/search-ttn/search-ttn-results/search-ttn-results.tsx
> +    getTtnData(props.ttn, isHistory, setSearchResult);
В залежностях вказано **props.ttn**. Загалом різниця в значенні властивості **props.ttn** не означає різниці в об'єкті **props**. Тому, теоретично, може виникнути ситуація, коли **props.ttn** буде взята із замикання якоїсь із попередніх ітерацій рендерингу.
Для уникнення таких ситуацій, бажано розіменовувати (деструктуризовувати) вкладені властивості із об'єктів.

2020-07-20 14:14 UTC, kol-93 commented on 26-sergey-urdinets/ts-project/src/components/pages/search-ttn/search-ttn-results/search-ttn-results.tsx
> +  const [searchResult, setSearchResult] = useState({
**useState()** вміє приймати функцію, яка повертає стартовий стан. Тому в подібних випадках краще загорнути стартовий стан-об'єкт в функцію, яка буде його повертати і винести її за межі компонента.

2020-07-23 13:54 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/info/info-services/info-services.tsx
> +
исправил, обновляется валидными данными

2020-07-23 13:54 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +          setSearchResults(data.result);
исправил, обновляется валидными данными

2020-07-23 13:54 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-map/simple-map/marker.tsx
> +    setShow(!isShow);
исправил

2020-07-23 13:54 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +            next={() =>
исправил

2020-07-23 13:55 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +  } else if (bool) {
исправил :)

2020-07-23 13:56 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +    setTableState(data.slice(0, 20));
исправил, запомнил

2020-07-23 13:56 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/search-ttn/result-output/result-output.tsx
> +function getImg(status: string) {
использовал в экшенах, а тут забыл про них, исправил

2020-07-23 13:56 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/search-ttn/search-ttn-results/search-ttn-results.tsx
> +    getTtnData(props.ttn, isHistory, setSearchResult);
запомнил, исправил

2020-07-23 13:57 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/search-ttn/search-ttn-results/search-ttn-results.tsx
> +  const [searchResult, setSearchResult] = useState({
если понял верно, то тоже исправил

2020-07-23 14:07 UTC, NeverSmileMan commented on 26-sergey-urdinets/ts-project/src/components/pages/departments/departments-list/infinite-table/infinite-table.tsx
> +      (item) => ~item.adress.search(new RegExp(value, 'i'))
1. побитовое отрицание превращает результат `String.search` в 0 если не найдено(где-то вычитал что для методов _/чаще массивов/_ возвращающих -1 как ошибку можно так делать) и так фильтруется массив
2. добавил валидацию для `value` в` RegExp`.

2020-07-28 09:30 UTC, kol-93 approved these changes

2020-07-28 15:30 UTC, kol-93 approved these changes

2020-07-28 15:30 UTC, merged