Feature/27 dmitriy dankov/dz 4
Evan-Kork/temabit-lections-2019 pull request #73
Opened 2019-10-25 11:47 UTC by Ar1dan7

2019-10-25 12:43 UTC, NeverSmileMan requested changes

2019-10-25 12:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/index.html
> +                </tr>
зачем пустые ячейки

2019-10-25 12:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/index.html
> +            <thead>
зачем пустые строки

2019-10-25 12:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/index.html
> +        <table style="color: black; text-align: left;">
в класс css засунь

2019-10-25 12:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/index.html
> +                </tr>
класс support-unknown можно всунуть в tr,  и в отдельных ячейках переписать класс на not-supported
(не знаю или так правильно но выглядит лучше)

2019-10-25 12:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/css/index.css
> +.notsupported {
пропустил дефис

2019-10-25 12:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/css/index.css
> +.supportedalfa {
пропустил дефис

2019-10-25 12:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/css/index.css
> +.supportunknown {
пропустил дефис

2019-10-25 12:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/css/index.css
> +.notsupportedalfa {
пропустил дефис

2019-10-25 12:43 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/index.html
> +                </tr>
класс row-border лучше (наверное) добавить в tr и в css и использовать селектор по классу для задания границы ячейкам:
tr[class~="row-border] td {
    border: 3px solid grey;
}
и класс not-supported вынести в tr, а где supported переписать (тоже не знаю или правильно xD)

2019-10-28 08:38 UTC, NeverSmileMan approved these changes

2019-10-31 18:17 UTC, AlexeyMatviichuk approved these changes

2019-10-31 18:44 UTC, NeverSmileMan requested changes

2019-10-31 18:44 UTC, NeverSmileMan commented on 27-dmitriy-dankov/dz-4/css/index.css
> +    border: 5px solid rgb(128,128,128)
строку не закрыл ";"
все цвета в hex а тут rgb  (#808080 - серый)

2019-10-31 22:31 UTC, NeverSmileMan approved these changes

2019-11-01 09:18 UTC, Evan-Kork commented on 27-dmitriy-dankov/dz-4/css/index.css
> +tr[class~="row-border"] td {
А якщо в стилях буде `color: red;` як назвеш данний клас?
Структура `tr[class~="row-border"] td`  аналогічна до `.row-border td`

2019-11-01 09:18 UTC, Evan-Kork commented on 27-dmitriy-dankov/dz-4/index.html
> +        <table class="legend">
Тут все нормально?

2019-11-07 14:35 UTC, Evan-Kork approved these changes

2019-11-07 14:36 UTC, merged